name: Build Container Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
          
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Webapp image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 600790893911.dkr.ecr.us-east-1.amazonaws.com/webapp_images:Islamiyat
        
    - name: Build and push MySQL image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 600790893911.dkr.ecr.us-east-1.amazonaws.com/mysql_images:Islamiyat
        

env:
  TAG_NAME: Islamiyat
